esphome:
  name: az32e01
  friendly_name: az32e01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zPMV1jCtpEzICLU3g6IN6lOwCs/KFX8kJV5nXPbBDwc="

ota:
  password: "ef68a3a8258224efeed014bac72ee342"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32E01 Fallback Hotspot"
    password: "1wOJbdi5JCPM"

captive_portal:

time:
  - platform: sntp
    id: esphome_time
    servers:
      - 0.pool.ntp.org

binary_sensor:
  - platform: status
    name: "E1 Status"

  - platform: template
    name: "E1 Sensor32 innen hell"
    lambda: |-
          if (id(source_sensor0).state > 70) {
            return true;
          } else {
            return false;
          }

  - platform: template
    name: "E1 Sensor33 aussen hell"
    lambda: |-
          if (id(source_sensor2).state > 70) {
            return true;
          } else {
            return false;
          }

sensor:
  - platform: wifi_signal
    name: "E1 WiFi Signal"
    update_interval: 10s #4s     #60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

  - platform: uptime
    name: E1 Uptime Sensor 

  - platform: dht
    pin: GPIO25
    model: DHT11
    temperature:
      name: "E1 Temperature Sensor25 innen"
    humidity:
      name: "E1 Humidity Sensor25 innen"
    update_interval: 60s #30s     60s eco

  - platform: dht
    pin: GPIO26
    model: DHT11
    temperature:
      name: "E1 Temperature Sensor26 aussen"
    humidity:
      name: "E1 Humidity Sensor26 aussen"
    update_interval: 60s #60s eco

  # Fotowiderstand (rechts intern):
  -  platform: adc
     id: source_sensor0
     name: "E1 Foto Sensor32 innen"
     pin: GPIO32  #33 orginal
     update_interval: 15s # 60s
     filters:
        - offset: 0.0
        - multiply: 1.0  #3.3
        - calibrate_linear:
          - 0.0733 -> -10.00     
          - 0.5 -> 60.00            
          - 1.045 -> 89.199        
     unit_of_measurement: "%"
     

  # Fotowiderstand (links extern):
  -  platform: adc
     id: source_sensor2
     name: "E1 Foto Sensor33 aussen"
     pin: GPIO33  #33 orginal
     update_interval: 20s # 60s
     filters:
        - offset: 0.0
        - multiply: 1.0  #3.3
        - calibrate_linear:
          - 0.0733 -> -10.00     
          - 0.5 -> 60.00            
          - 1.045 -> 89.199        
     unit_of_measurement: "%"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "E1 IP Address"
    ssid:
      name: "E1 Connected SSID"
