esphome:
  name: az32e03
  friendly_name: az32e03

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "A1Rke0bFYmutM+Aczw1j2C44bdki48GCu8X/v/Sf1z8="

ota:
  password: "e3cdad2c4d85dec24e993e9dce0cf959"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32E03 Fallback Hotspot"
    password: "WawVqHa0Obya"

captive_portal:

time:
  - platform: sntp
    id: esphome_time
    servers:
      - 0.pool.ntp.org

binary_sensor:
  - platform: status
    name: "E3 Status"

  - platform: gpio
    pin: GPIO34 #18
    id: taster1   
    name: taster1
    on_press:
      then:
      - switch.toggle: my_led 
      - delay: 500ms

  - platform: gpio
    pin: GPIO35 #19
    id: taster2
    name: taster2   
    on_press:
      then:
      - switch.toggle: my_led 
      - delay: 1000ms

  - platform: template
    name: "E3 Sensor32 innen hell"
    lambda: |-
          if (id(source_sensor0).state > 70) {
            return true;
          } else {
            return false;
          }

  - platform: template
    name: "E3 Sensor33 aussen hell"
    lambda: |-
          if (id(source_sensor2).state > 70) {
            return true;
          } else {
            return false;
          }

sensor:
  - platform: wifi_signal
    name: "E3 WiFi Signal"
    update_interval: 10s #4s     #60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

  - platform: uptime
    name: E3 Uptime Sensor 

  - platform: dht
    pin: GPIO25
    model: DHT11
    temperature:
      name: "E3 Temperature Sensor25 innen"
    humidity:
      name: "E3 Humidity Sensor25 innen"
    update_interval: 60s #30s     60s eco

  - platform: dht
    pin: GPIO26
    model: DHT11
    temperature:
      name: "E3 Temperature Sensor26 aussen"
    humidity:
      name: "E3 Humidity Sensor26 aussen"
    update_interval: 60s #60s eco

  # Fotowiderstand (rechts intern):
  -  platform: adc
     id: source_sensor0
     name: "E3 Foto Sensor32 innen"
     pin: GPIO32  #33 orginal
     update_interval: 15s # 60s
     filters:
        - offset: 0.0
        - multiply: 1.0  #3.3
        - calibrate_linear:
          - 0.0733 -> -10.00     
          - 0.5 -> 60.00            
          - 1.045 -> 89.199        
     unit_of_measurement: "%"
     

  # Fotowiderstand (links extern):
  -  platform: adc
     id: source_sensor2
     name: "E3 Foto Sensor33 aussen"
     pin: GPIO33  #33 orginal
     update_interval: 20s # 60s
     filters:
        - offset: 0.0
        - multiply: 1.0  #3.3
        - calibrate_linear:
          - 0.0733 -> -10.00     
          - 0.5 -> 60.00            
          - 1.045 -> 89.199        
     unit_of_measurement: "%"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "E3 IP Address"
    ssid:
      name: "E3 Connected SSID"

switch:
  - platform: gpio
    pin: GPIO27  #27 
    id: my_led
    name: "Relais1"

    