# esphome config file with all features
substitutions:
  devicename: az32f02 #ehmtx8266
  friendly_name: f02
  ledpin: GPIO26  # 02
  board: esp32dev # d1_mini
  loglevel: DEBUG

external_components:
  - source:
      type: git
      url: https://github.com/lubeda/EsphoMaTrix

esphome:
  name: $devicename # az32f02
  friendly_name: $friendly_name
  comment: 192.168.1.146, bme280, Display-Matrix2
  on_boot:
    priority: -100
    then: 
      - ehmtx.text.color:
          id: rgb8x32
          red: !lambda return 200;
          green: !lambda return 100;
          blue: !lambda return 50;
      - ehmtx.clock.color:
          id: rgb8x32
          red: !lambda return 150;
          green: !lambda return 0;
          blue: !lambda return 100;
      - ehmtx.today.color:
          id: rgb8x32
          red: !lambda return 0;
          green: !lambda return 100;
          blue: !lambda return 0;
      - ehmtx.weekday.color:
          id: rgb8x32
          red: !lambda return 0;
          green: !lambda return 0;
          blue: !lambda return 100;
      - ehmtx.alarm.color:
          id: rgb8x32
          red: !lambda return 200;
          green: !lambda return 150;
          blue: !lambda return 30;

web_server:
  port: 80
  version: 2
  local: true
  auth:
    username: f02
    password: control

esp32:
  board: $board # esp32dev
#  framework:
#    type: arduino

font:
  - file: _fonts/monobit.ttf  # !!!
    id: ehmtx_font
    size: 16
    glyphs:  |
      !?"%()+*=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz€@<>/

logger:
 level: $loglevel

# Enable Home Assistant API
api:
  encryption:
    key: "LU8hfj9m3PNMJkk+bXy56EPVBcGPNscSuas76ukG0u4="
  reboot_timeout: 0s
  services:
    - service: write_text
      variables:
        message: string
      then:
        - globals.set:
            id: matrix_text1
            value: !lambda 'return message;'

        - delay: 20s
        - globals.set:
            id: matrix_text1
            value: !lambda 'return "";'

ota:
  password: "11a96f7c81378b3c6420f08499de6818"

wifi:
  ssid: 6wlan # !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none
#  reboot_timeout: 0s
#  domain: ".local"       #  domain  .fritz.box 
#  output_power: 20dB
#  fast_connect: true

#  manual_ip:
#    static_ip: 192.168.1.172 # 3EG5-Garten (A) = Bereich ,  d7
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 # subnet2 test 255.255.0.0
#    dns1: 192.168.1.1
#    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Az32D07 Fallback Hotspot"
    password: "B4fPJ7nxBQSk"

captive_portal:
#####################################################################################
#----------------------------
#   Globale Variablen
#----------------------------
globals:
  - id: x
    type: std::string
    restore_value: no
    initial_value: ''

  - id: matrix_text1
    type: std::string
    restore_value: no
    initial_value: ''

  - id: anim_pos
    type: int
    restore_value: no
    initial_value: '0'

  - id: display_page   ##Test2
    type: int
    restore_value: no
    initial_value: '1'

  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'

  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'

  - id: page
    type: int
    initial_value: "1"
#####################################################################################
light:
  - platform: neopixelbus
    id: ehmtx_light
    type: GRB
    variant: WS2812
    pin: $ledpin
    num_leds: 256
    color_correct: [30%, 30%, 30%]
    name: "$devicename Light"
    restore_mode: ALWAYS_OFF
    on_turn_on:
      lambda: |-
         id(ehmtx_display)->set_enabled(false);
    on_turn_off:
       lambda: |-
         id(ehmtx_display)->set_enabled(true);
#####################################################################################
  - platform: neopixelbus
    id: rgb_light
    type: GRB
    variant: WS2812x
    pin: GPIO23
    num_leds: 1
    name: "${friendly_name} RGB Light"
    method:
      type: esp32_rmt
      channel: 0
#####################################################################################
time:
  - platform: homeassistant
    id: ehmtx_time

#parallel dauerhaft versuchen über wifi die Zeit zu syncen
  - platform: homeassistant
    id: my_time
    #on_time_sync:
    #  then:
        #- logger.log: "Synchronized system clock"
        #update der RTC
        #ds1302.write_time:
         #id: ds1302_time

  - platform: homeassistant
    id: my_time2
    on_time:
      - seconds: /10
        then:
#        - light.toggle: rgb_light

#####################################################################################
# Binary Sensor definition
# Präsenzsensor
binary_sensor:
  - platform: template
    name: "${friendly_name} speedtestdl 01"
    device_class: CONNECTIVITY
    lambda: |-
      if (id(speedtestdownload).state > 1) {
        // car is in the garage
        return true;
      } else {
        // no car
        return false;
      } 

  - platform: template
    name: "${friendly_name} speedtestup 02"
    device_class: CONNECTIVITY
    lambda: |-
      if (id(speedtestupload).state > 1) {
        // car is in the garage
        return true;
      } else {
        // no car
        return false;
      } 
#####################################################################################
  - platform: status
    name: "${friendly_name} Online"
    id: ink_ha_connected
  - platform: gpio
    pin: 
      number: GPIO33
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();
            
    on_release:
      then:

  - platform: gpio
    pin: GPIO36 #links oben orange
    id: taster1   
    name: "${friendly_name} taster1"
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then: 
       lambda: |-
         id(page) = (id(page) - 1);
         if (id(page) < 1) {
          id(page) = 1;
         }

  - platform: gpio
    pin: GPIO39 #rechts oben sw
    id: taster2
    name: "${friendly_name} taster2"   
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then: 
       lambda: |-
         id(page) = (id(page) + 1);
         if (id(page) > 4) {
          id(page) = 4;
         }

  - platform: gpio
    pin: GPIO34 #links unten
    id: taster3   
    name: "${friendly_name} taster3"
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then: 
       lambda: |-
         id(page) = 1;


  - platform: gpio
    pin: GPIO35 #rechts unten
    id: taster4
    name: "${friendly_name} taster4"   
    filters:
      - delayed_on: 30ms
      - delayed_off: 30ms
    on_press:
      then: 
       lambda: |-
         id(page) = 4;

display:
  - platform: addressable_light
    id: ehmtx_display
    addressable_light_id: ehmtx_light
    width: 32
    height: 8
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
    rotation: 0°
    update_interval: 16ms
    auto_clear_enabled: true
    lambda: |-
      id(rgb8x32)->tick();
      id(rgb8x32)->draw();

#####################################################################################
sensor:
  - platform: homeassistant
    name: "Matrix Text"
    id: matrix_text
    entity_id: input_text.matrix_text1  # !!!helper2

  - platform: homeassistant
    id: speedtestdownload
    entity_id: sensor.speedtest_download
    internal: true

  - platform: copy # Reports the WiFi signal strength in %
    source_id: speedtestdownload
    name: "${friendly_name} speedtestdl"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"  

  - platform: homeassistant
    id: speedtestupload
    entity_id: sensor.speedtest_upload
    internal: true
    filters: 
      - round: 1 # will round to 1 decimal place

  - platform: copy # Reports the WiFi signal strength in %
    source_id: speedtestupload
    name: "${friendly_name} speedtestup"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%" 

  - platform: internal_temperature
    name: "${friendly_name} ESP Temperature"
    id: sys_esp_temperature

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_db
    update_interval: 4s     #60s 120s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    entity_category: "diagnostic"
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${friendly_name} WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"  #Signal %
    entity_category: "diagnostic"

  - platform: uptime
    name: "${friendly_name} Uptime Sensor" 
    id: uptimesensor
#####################################################################################
# Text Sensor definition
# WIFI Info Bereich
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
    mac_address:
      name: "${friendly_name} Mac Wifi Address"

#####################################################################################
switch:
  - platform: restart
    name: "${friendly_name} Restart"
    id: d07_restart  

  - platform: gpio
    pin: GPIO27
    id: pin27
    name: "${friendly_name} 27Relais1"

  - platform: gpio
    pin: GPIO19
    id: pin19
    name: "${friendly_name} 19Relais2"

  - platform: gpio
    pin: GPIO18
    id: pin18
    name: "${friendly_name} 18Relais3"

  - platform: gpio
    pin: GPIO4
    id: pin4
    name: "${friendly_name} 04Relais4"

#  - platform: gpio
 #   pin: GPIO2
 #   id: pin2
 #   name: "${friendly_name} 02Relais5"
#####################################################################################
image:
   - file: _icons/1pixel.gif
     id: breaking20237

animation:
  - file: _icons/1pixel.gif
    id: breaking202371

ehmtx:
  id: rgb8x32
  time_component: ehmtx_time
  matrix_component: ehmtx_display
  clock_time: 10    # seconds
  screen_time: 15   # seconds
  clock_interval: 25
  font_id: ehmtx_font
  show_dow: true   # day of week
  icons2html: false # generate html with con overview
  brightness: 80 # percent
  time_format: "%H:%M"
  date_format: "%d.%m."
  week_start_monday: true
  xoffset: 1
  yoffset: 6
  scroll_count: 2
  scroll_interval: 80
  frame_interval: 192

  on_next_screen: # trigger on screen change 
    lambda: |-
        ESP_LOGD("TriggerTest","Iconname: %s",x.c_str());
        ESP_LOGI("TriggerTest","Text: %s",y.c_str());

  on_next_clock: # trigger on clock display
    then:
    - ehmtx.clock.color:
          id: rgb8x32
          red: !lambda return 150;
          green: !lambda return rand() % 255;
          blue: !lambda return 100;
#####################################################################################
  icons: 
    - id: xani
      lameid: 6075
    - id: xsta
      lameid: 11236
    - url: https://developer.lametric.com/content/apps/icon_thumbs/48720.gif
      pingpong: true
      id: pipo
      frame_duration: 300
    - lameid: 5965
      frame_duration: 180
      id: d180
    - lameid: 5965
      frame_duration: 80
      id: d080
    - id: fullscreen
      file: _icons/sample8x32.gif
    - id: samplegif
      file: _icons/sample8x8.gif
#####################################################################################
    - id: icon_clock                   # analog clock run
      file: _icons/82_icon_clock.gif 

    - id: icon_tetris                 # tetris red run
      file: _icons/119_icon_thumb.gif

    - id: icon_hearth                 # herz pulsiert
      file: _icons/230_icon_hearth.gif

    - id: icon_redpulse                 # roter blink effekt
      file: _icons/681_icon_thumb.gif

    - id: icon_temp                    # analog temp !!! no ani is png
      file: _icons/2056_icon_temp.png

    - id: icon_coffee                  # analog cafe hot
      file: _icons/6396_icon_thumb.gif

    - id: icon_spaceinv                 # analog cafe hot
      file: _icons/7555_icon_thumb.gif

    - id: icon_rgbclock               # analog cafe hot
      file: _icons/7655_icon_thumb.gif

    - id: icon_trashyellow1            # gelbe tonne 1 static pic !!! no ani is png
      file: _icons/11005_icon_thumb.png

    - id: icon_redbluepulse           # roter  blauer blink effekt
      file: _icons/11188_icon_thumb.gif

    - id: icon_trashgrey1            # schwarze tonne static pic !!! no ani is png
      file: _icons/11979_icon_thumb.png

    - id: icon_trashblue1            # blaue tonne 1 static pic !!! no ani is png
      file: _icons/12060_icon_thumb.png

    - id: icon_house1                # haus alarmanlage
      file: _icons/19786_icon_thumb.gif

    - id: icon_eye1             # auge kuckt
      file: _icons/20094_icon_thumb.gif

    - id: icon_trashyellow2            # gelbe tonne 2 anideckel  pic !!!  is gif
      file: _icons/38054_icon_tyellowcap.gif     

    - id: icon_trashcar               # muell-lkw ani pic !!!  is gif
      file: _icons/51975_icon_trashcar.gif

    - id: icon_trashblue2                  # blaue hin und gelbe weg mit ! tonne 2 ani pic !!!  is gif
      file: _icons/53807_icon_trashblue.gif

    - id: icon_trashyellow3              # gelbe tonne 3 ani rollen pic !!!  is gif
      file: _icons/56162_icon_thumb.gif

    - id: icon_trashyellow0             # schwarze tonne static pic !!! no ani is png
      file: _icons/56166_icon_thumb.png

    - id: icon_trashgrey0           # blaue tonne 1 static pic !!! no ani is png
      file: _icons/56473_icon_thumb.png

    - id: icon_trashyellow4              # voll vorbringen gelbe tonne 3 ani rollen2 pic !!!  is gif
      file: _icons/56476_icon_trashyellow.gif




