# esphome config file with all features
substitutions:
  devicename: esphome-web-7771f4
  friendly_name: fn32s3s1
#  ledpin: GPIO26  # 02

esphome:
  name: $devicename
  friendly_name: $friendly_name
  comment: 192.168.1.128, Cam S1, Kueche 

esp32:
  board: esp32dev
  framework:
    type: arduino

preferences:
  flash_write_interval:  1min # 10sMAX 1min default

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+eUCc/JvbZFHTI/Hf1TEJLFilZ6pj85skub48Xsf+7o="

ota:

# Example configuration entry with additional service , ping port
mdns:
  disabled: false #default

wifi:
  ssid: 6wlan # !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none
#  reboot_timeout: 0s
#  #domain: ".fritz.box"
#  output_power: 20dB
#  fast_connect: true

#  manual_ip:
#    static_ip: 192.168.1.201  #  fn32s3s1  cam 1  esp32s1_cam ESP32Cam FN1 status
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 # subnet2 test 255.255.0.0
#    dns1: 192.168.1.1
#    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-7771F4"
    password: "UjQI8l89Pstw"

captive_portal:
#web_server:
#  port: 80
#  version: 2
#  local: true
#  auth:
#    username: cam1
#    password: control

#ESP32s3WROVER_cam 1x USB_Pinout Cam.png S1
esp32_camera:
  name: esp32s1_cam
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  resolution: 640x480 #640x480 (VGA, default)
  max_framerate: 10 fps #From 10 (best) to 63 (worst)
  idle_framerate: 0.1 fps
  jpeg_quality: 10  #10default 23 not fluid
  vertical_flip: False
  horizontal_mirror: False

output:
  - platform: gpio
    pin: GPIO2
    id: light_output
    #inverted: True
    
binary_sensor:
  - platform: status
    name: "ESP32Cam FN1 status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32Cam FN1 WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: light_output
    name: "ESP32Cam FN1 light"
    #restore_mode: ALWAYS_OFF
    #restore_mode: RESTORE_DEFAULT_OFF
    