# esphome config file with all features
substitutions:
  devicename: esphome-web-e911d0
  friendly_name: fn32s3
#  ledpin: GPIO26  # 02

esphome:
  name: $devicename
  friendly_name: $friendly_name
  comment: 192.168.1.135, Cam S3, Balkon

esp32:
  board: esp32-s3-devkitc-1 #esp32s3camlcd #esp-wrover-kit #esp32-s3-devkitc-1
  framework:
    type: arduino
    
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1XuPbtJyDAby9yWsl+4lHo7CpbyjaPLAJ/vcxkQEwu0="

ota:
  password: "f17102930885e79c7385131a54d3fdec"

wifi:
  ssid: 6wlan # !secret wifi_ssid
  password: !secret wifi_password
#  power_save_mode: none
#  reboot_timeout: 0s
#  #domain: ".fritz.box"
#  output_power: 20dB
#  fast_connect: true

#  manual_ip:
#    static_ip: 192.168.1.203 # Cam 3 , fn32s3 , esp32s3_cam, ESP32Cam FN3
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0 # subnet2 test 255.255.0.0
#    dns1: 192.168.1.1
#    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-E911D0"
    password: "ntwEYaFNNcsA"

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/MichaKersloot/esphome_custom_components
    components: [ esp32_camera ]
    
#ESP32s3WROVER_cam 2x USB_Pinout Cam.png esp32-s3-devkitc-1
esp32_camera:
  name: esp32s3_cam
  external_clock:
    pin: GPIO15 #cam_xclk 21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4 #4 cam_siod 26
    scl: GPIO5 #5 cam_sioc 27
  # 8x datalines , cam_y2 4, cam_y3 5, cam_y4 18, cam_y5 19, cam_y6 36, cam_y7 39, cam_y8 34, cam_y9 35
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6 #cam_vysnc 25
  href_pin: GPIO7 #cam_href 23
  pixel_clock_pin: GPIO13 #cam_pclk 22
  resolution: 640x480 #640x480 (VGA, default)
  max_framerate: 25 fps #From 10 (best) to 63 (worst)
  idle_framerate: 0.1 fps
  jpeg_quality: 25  #10default 23 not fluid
  vertical_flip: False
  horizontal_mirror: False

output:
  - platform: gpio
    pin: GPIO2
    id: gpio_2

binary_sensor:
  - platform: status
    name: "ESP32Cam FN3 status"
    
sensor:
  - platform: wifi_signal
    name: "ESP32Cam FN3 WiFi Signal"
    update_interval: 60s
    
light:
  - platform: binary
    output: gpio_2
    name: "ESP32Cam FN3 light"